name = "ellington"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "postgresql://neondb_owner:npg_5Av2oRzTwtdE@ep-aged-hat-axkhq856-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require"
JWT_SECRET = "ellington-production-secret-2026"
ADMIN_EMAIL = "admin@developer.com"
ADMIN_PASSWORD = "admin123"
