import { useEffect, useMemo, useState } from "react";
import { AC } from "../../lib/format";

const GROUPS: [string, string[]][] = [
  ["Sales", ["Sales register", "Inventory status", "Price list", "Sales velocity", "Agent performance", "Broker performance", "Discount analysis", "Lead source ROI"]],
  ["Finance", ["Collections summary", "Ageing analysis", "Cashflow forecast", "Receipts register", "Invoice register", "VAT summary", "Escrow reconciliation", "Commission payable"]],
  ["Compliance", ["Oqood registration status", "KYC completeness", "Document expiry", "RERA submission log", "Audit trail export", "Advertising permit status"]],
  ["Project", ["Construction progress", "Milestone variance", "Handover readiness", "Snagging summary"]],
];

const SCHEDULED = [
  ["Portfolio summary", "K. Al Fahim, board@", "Weekly · Mon 08:00", "PDF board pack", "31 Aug 2026"],
  ["Ageing analysis", "Finance team", "Weekly · Fri 17:00", "XLSX", "28 Aug 2026"],
  ["Oqood pending", "Legal", "Daily · 09:00", "CSV", "26 Aug 2026"],
  ["Broker performance", "Sales director", "Monthly · 1st", "PDF", "01 Sep 2026"],
];

const ALL_REPORTS = GROUPS.flatMap((g) => g[1]);

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

const bullet = (s: string) => s.replace(/\s+/g, "-").toLowerCase();

function csvFor(name: string) {
  const head = "Report,Field,Value";
  const body = [
    "Date," + new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }),
    "Scope," + "All projects",
    "Generated by," + "Ellington ERP",
  ].map((r) => r + ",").join("\n");
  return head + "\n" + body;
}

function xlsFor(name: string) {
  return "Report\tGenerated\tScope\n" + name + "\t" + new Date().toLocaleDateString("en-GB") + "\tAll projects\n";
}

function pdfFor(name: string, title: string, sub: string) {
  import("../../lib/pdf").then(({ reportPdf }) => reportPdf(name, title, sub));
}

export default function ReportsScreen() {
  const [open, setOpen] = useState(false);
  const [report, setReport] = useState(ALL_REPORTS[0]);
  const [format, setFormat] = useState("CSV");
  const [err, setErr] = useState("");

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") { setOpen(false); setErr(""); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  const groups = useMemo(
    () =>
      GROUPS.map((g) => ({
        label: g[0],
        items: g[1].map((n, i) => ({
          name: n,
          last: i % 3 === 0 ? "Run 2 days ago" : i % 3 === 1 ? "Run yesterday" : "Never run",
          star: i < 2 ? "#E2A33C" : "#DDE0E8",
        })),
      })),
    []
  );

  const runCsv = (name: string) => download(new Blob([csvFor(name)], { type: "text/csv;charset=utf-8;" }), "ellington-" + bullet(name) + ".csv");

  const generate = () => {
    if (!report) { setErr("Choose a report."); return; }
    if (format === "PDF") pdfFor(report, "Custom report", "Generated 25 Aug 2026 · All projects");
    else if (format === "XLSX") download(new Blob([xlsFor(report)], { type: "application/vnd.ms-excel" }), "ellington-" + bullet(report) + ".xls");
    else download(new Blob([csvFor(report)], { type: "text/csv;charset=utf-8;" }), "ellington-" + bullet(report) + ".csv");
    setOpen(false);
    setErr("");
  };

  return (
    <div>
      <div style={{ display: "flex", alignItems: "flex-end", gap: 16, marginBottom: 20 }}>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 26, fontWeight: 800, letterSpacing: "-.03em", lineHeight: 1.15 }}>Reports</div>
          <div style={{ fontSize: 13, color: "#6B7180", fontWeight: 500, marginTop: 5 }}>27 standard reports · XLSX, CSV, branded PDF, board pack</div>
        </div>
        <button onClick={() => { setErr(""); setOpen(true); }} style={{ height: 38, borderRadius: 12, border: "1px solid #EDEEF3", background: "#fff", padding: "0 14px", fontFamily: "inherit", fontSize: 12.5, fontWeight: 700, color: "#4A5060", cursor: "pointer" }}>Custom report builder</button>
        <button onClick={() => pdfFor("Board pack", "Board pack", "Generated 25 Aug 2026 · All projects")} style={{ height: 38, borderRadius: 12, background: "#14161F", color: "#fff", border: 0, padding: "0 16px", fontFamily: "inherit", fontSize: 12.5, fontWeight: 700, cursor: "pointer" }}>Assemble board pack</button>
      </div>

      {groups.map((g) => (
        <div key={g.label} style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: ".09em", color: "#9AA0AE", textTransform: "uppercase", marginBottom: 12 }}>{g.label}</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 12 }}>
            {g.items.map((r) => (
              <div key={r.name} style={{ background: "#fff", borderRadius: 16, padding: "16px 18px", boxShadow: "0 1px 3px rgba(20,22,31,.04)", display: "flex", flexDirection: "column", gap: 10 }}>
                <div style={{ display: "flex", alignItems: "flex-start", gap: 8 }}>
                  <span style={{ flex: 1, fontSize: 12.5, fontWeight: 700, letterSpacing: "-.01em", lineHeight: 1.35 }}>{r.name}</span>
                  <span style={{ color: r.star, fontSize: 13, flex: "none" }}>★</span>
                </div>
                <div style={{ fontSize: 10.5, color: "#9AA0AE", fontWeight: 600 }}>{r.last}</div>
                <button onClick={() => runCsv(r.name)} style={{ height: 30, borderRadius: 10, border: "1px solid #EDEEF3", background: "#fff", fontFamily: "inherit", fontSize: 11, fontWeight: 700, color: AC, cursor: "pointer" }}>Run</button>
              </div>
            ))}
          </div>
        </div>
      ))}

      <div style={{ background: "#fff", borderRadius: 20, boxShadow: "0 1px 3px rgba(20,22,31,.04)", overflow: "hidden" }}>
        <div style={{ padding: "20px 24px 4px", fontSize: 15, fontWeight: 700, letterSpacing: "-.015em" }}>Scheduled deliveries</div>
        <div style={{ display: "grid", gridTemplateColumns: "1.2fr 1.2fr 1fr 140px 110px", gap: 12, padding: "14px 24px", fontSize: 9.5, fontWeight: 700, letterSpacing: ".07em", color: "#9AA0AE", textTransform: "uppercase", borderBottom: "1px solid #EDEEF3" }}>
          <span>Report</span><span>Recipients</span><span>Frequency</span><span>Format</span><span>Next run</span>
        </div>
        {SCHEDULED.map((r) => (
          <div key={r[0]} style={{ display: "grid", gridTemplateColumns: "1.2fr 1.2fr 1fr 140px 110px", gap: 12, alignItems: "center", padding: "0 24px", height: 44, borderBottom: "1px solid #F6F7FA" }}>
            <span style={{ fontSize: 12, fontWeight: 700 }}>{r[0]}</span>
            <span style={{ fontSize: 11.5, color: "#6B7180", fontWeight: 600 }}>{r[1]}</span>
            <span style={{ fontSize: 11.5, color: "#6B7180", fontWeight: 600 }}>{r[2]}</span>
            <span style={{ fontSize: 11.5, color: "#6B7180", fontWeight: 600 }}>{r[3]}</span>
            <span style={{ fontSize: 11.5, fontWeight: 700 }}>{r[4]}</span>
          </div>
        ))}
      </div>

      {open && (
        <div onMouseDown={() => { setOpen(false); setErr(""); }} style={{ position: "fixed", inset: 0, background: "rgba(20,22,31,.42)", display: "grid", placeItems: "center", zIndex: 80, padding: 24 }}>
          <div onMouseDown={(e) => e.stopPropagation()} style={{ background: "#fff", borderRadius: 22, padding: "26px 28px", width: "100%", maxWidth: 520, boxShadow: "0 24px 60px rgba(20,22,31,.25)" }}>
            <div style={{ fontSize: 18, fontWeight: 800, letterSpacing: "-.02em" }}>Custom report builder</div>
            <div style={{ fontSize: 12.5, color: "#6B7180", fontWeight: 500, marginTop: 4, lineHeight: 1.5 }}>Pick any standard report and an output format. The file downloads instantly.</div>
            <div style={{ display: "flex", flexDirection: "column", gap: 14, marginTop: 20 }}>
              <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                <span style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: ".06em", color: "#9AA0AE", textTransform: "uppercase" }}>Report</span>
                <select
                  value={report}
                  onChange={(e) => setReport(e.target.value)}
                  style={{ height: 38, borderRadius: 10, border: "1px solid #EDEEF3", background: "#FAFBFD", padding: "0 12px", fontFamily: "inherit", fontSize: 13, fontWeight: 600, outline: "none" }}
                >
                  {ALL_REPORTS.map((n) => <option key={n} value={n}>{n}</option>)}
                </select>
              </label>
              <label style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                <span style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: ".06em", color: "#9AA0AE", textTransform: "uppercase" }}>Format</span>
                <select
                  value={format}
                  onChange={(e) => setFormat(e.target.value)}
                  style={{ height: 38, borderRadius: 10, border: "1px solid #EDEEF3", background: "#FAFBFD", padding: "0 12px", fontFamily: "inherit", fontSize: 13, fontWeight: 600, outline: "none" }}
                >
                  {["CSV", "XLSX", "PDF"].map((f) => <option key={f} value={f}>{f}</option>)}
                </select>
              </label>
              {err && <div style={{ fontSize: 11.5, fontWeight: 600, color: "#E5484D" }}>{err}</div>}
            </div>
            <div style={{ display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 22 }}>
              <button
                onClick={() => { setOpen(false); setErr(""); }}
                style={{ height: 38, borderRadius: 12, border: "1px solid #EDEEF3", background: "#fff", padding: "0 16px", fontFamily: "inherit", fontSize: 12.5, fontWeight: 700, color: "#4A5060", cursor: "pointer" }}
              >Cancel</button>
              <button
                onClick={generate}
                style={{ height: 38, borderRadius: 12, background: AC, color: "#fff", border: 0, padding: "0 20px", fontFamily: "inherit", fontSize: 12.5, fontWeight: 700, cursor: "pointer" }}
              >Generate report</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}