import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { AC } from "./format";

type ProjectRow = {
  code: string;
  name: string;
  loc: string;
  units: number;
  sold: number;
  gdv: number;
  soldV: number;
  coll: number;
  cons: number;
  status: string;
  flag: boolean;
};

type FinTile = { label: string; value: string; note: string; bad?: boolean };
type FinRow = { code: string; name: string; gdv: string; soldV: string; coll: string; out: string; comm: string; dld: string; net: string };

const AED = "AED ";
const fmt = (n: number) => n.toLocaleString("en-US");

function downloadBlob(doc: jsPDF, filename: string) {
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export { downloadBlob };

export function exportPortfolioPdf(projects: ProjectRow[], kpis: { label: string; value: string; note: string }[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text("Portfolio position · 5 projects · 850 units · 25 Aug 2026", 14, 24);

  // KPI summary
  let y = 44;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Summary", 14, y);
  y += 3;
  const half = Math.ceil(kpis.length / 2);
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Note"]],
    body: kpis.map((k) => [k.label, k.value, k.note || ""]),
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Value position by project
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Value position by project", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Code", "Project", "Location", "Units", "Sold", "GDV (M)", "Sold value (M)", "Coll %", "Cons %", "Status"]],
    body: projects.map((p) => [p.code, p.name, p.loc, String(p.units), String(p.sold), fmt(p.gdv), fmt(p.soldV), p.coll + "%", p.cons + "%", p.status]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2, valign: "middle" },
    columnStyles: { 0: { fontStyle: "bold", textColor: [79, 70, 245] } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // Footer
  const lines = doc.splitTextToSize("Collected AED 819.6M · Outstanding receivable AED 502.4M · Overdue AED 31.4M · Units available 316 of 850. Generated by Ellington ERP.", pageW - 28);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  doc.text(lines, 14, y);
  y += lines.length * 5;

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · Portfolio position", 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }

  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "ellington-portfolio-position.pdf";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function exportFinancialsPdf(tiles: FinTile[], rows: FinRow[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text("Consolidated financials · 5 SPVs · YTD to 25 Aug 2026", 14, 24);

  let y = 44;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Note"]],
    body: tiles.map((t) => [t.label, t.value, t.note || ""]),
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Position by project entity", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Code", "Entity", "GDV", "Sold", "Collected", "Outstanding", "Commission", "DLD", "Net cash"]],
    body: rows.map((r) => [r.code, r.name, r.gdv, r.soldV, r.coll, r.out, r.comm, r.dld, r.net]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2, valign: "middle" },
    columnStyles: { 0: { fontStyle: "bold", textColor: [79, 70, 245] } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  const lines = doc.splitTextToSize("Revenue recognised AED 604.2M · Cash collected AED 819.6M · VAT payable AED 8.4M · Commission accrued AED 26.1M. Generated by Ellington ERP.", pageW - 28);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  doc.text(lines, 14, y);

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · Consolidated financials", 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }

  downloadBlob(doc, "ellington-board-pack.pdf");
}

export function reportPdf(title: string, sub: string, meta: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text(sub, 14, 24);

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, 14, y);
  y += 4;
  doc.setFontSize(9.5);
  doc.setTextColor(110, 113, 128);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(meta, pageW - 28);
  doc.text(lines, 14, y);
  y += lines.length * 5 + 6;

  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: [
      ["Report", title],
      ["Generated", "25 Aug 2026"],
      ["Scope", "All projects"],
      ["Generated by", "Ellington ERP"],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · Reports", 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }

  downloadBlob(doc, "ellington-" + title.replace(/\s+/g, "-").toLowerCase() + ".pdf");
}

type UnitDoc = {
  id: string;
  typ: string;
  beds: number;
  area: number;
  view: string;
  f: number;
  psf: number;
  price: number;
  status: string;
  buyer: string;
};

const line = (doc: jsPDF, x: number, y: number, w: number, color: [number, number, number]) => {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(0.4);
  doc.line(x, y, x + w, y);
};

function docBase(sub: string): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(10.5);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text(sub, 14, 24);
  return doc;
}

function docFooter(doc: jsPDF, subject: string) {
  const pageSize = doc.internal.pageSize;
  const pageH = pageSize.getHeight();
  const pageW = pageSize.getWidth();
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · " + subject, 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }
}

export function exportUnitSoa(u: UnitDoc, milestones: { seq: string; label: string; due: string; pct: string; amount: string; status: string }[]) {
  const doc = docBase("Ellington Holdings · Statement of account");
  const pageW = doc.internal.pageSize.getWidth();
  const { net, collected, outstanding } = soaNumbers(u);
  const buyerName = u.buyer === "—" ? "Unassigned" : u.buyer;

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Statement of Account", 14, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Buyer: " + buyerName, 14, y);
  doc.text("Unit: " + u.id + " · " + u.typ + " · Level " + u.f + " · " + u.area.toLocaleString("en-US") + " sq.ft · " + u.view + " view", 14, y + 5);
  doc.text("Contract price: " + "AED " + u.price.toLocaleString("en-US"), 14, y + 10);
  doc.text("State: " + u.status, 14, y + 15);
  y += 26;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 22, 31);
  doc.text("Balance summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Amount"]],
    body: [
      ["Net contract price", "AED " + fmt(net)],
      ["Collected to date", "AED " + fmt(collected)],
      ["Outstanding balance", "AED " + fmt(outstanding)],
      ["Next payment due", "14 Sep 2026"],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Payment schedule", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["#", "Milestone", "Due", "%", "Amount", "Status"]],
    body: milestones.map((m) => [m.seq, m.label, m.due, m.pct, m.amount, m.status]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 4: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("This statement is generated automatically by Ellington ERP and reflects the outstanding obligations as at 25 Aug 2026. Please quote the unit reference when making payment.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Statement of account");
  downloadBlob(doc, "soa-" + u.id.toLowerCase() + ".pdf");
}

export function exportUnitEoi(u: UnitDoc) {
  const doc = docBase("Ellington Holdings · Expression of interest");
  const pageW = doc.internal.pageSize.getWidth();
  const buyerName = u.buyer === "—" ? "Prospective buyer" : u.buyer;
  const { net } = soaNumbers(u);

  let y = 48;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Expression of Interest", 14, y);
  y += 9;
  doc.setTextColor(70, 73, 80);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  const body = doc.splitTextToSize(
    "This Expression of Interest (EOI) confirms " + buyerName + " has expressed an interest in Unit " + u.id +
    ", a " + u.beds + "-bedroom " + u.typ.toLowerCase() + " of " + u.area.toLocaleString("en-US") + " sq.ft at " + u.view.toLowerCase() + " view on Level " + u.f +
    ", priced at AED " + u.price.toLocaleString("en-US") + " (AED " + u.psf.toLocaleString("en-US") + " per sq.ft).", pageW - 28);
  doc.text(body, 14, y);
  y += body.length * 5.4 + 8;

  autoTable(doc, {
    startY: y,
    head: [["Field", "Detail"]],
    body: [
      ["Unit reference", u.id],
      ["Typology", u.typ + " · " + u.beds + " bedroom"],
      ["Floor / view", "Level " + u.f + " · " + u.view + " view"],
      ["Area", u.area.toLocaleString("en-US") + " sq.ft"],
      ["Rate", "AED " + u.psf.toLocaleString("en-US") + " /sq.ft"],
      ["Indicative price", "AED " + u.price.toLocaleString("en-US")],
      ["Net price (after 5.0% discount)", "AED " + fmt(net)],
      ["Status", u.status],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 6;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("This EOI is non-binding and does not constitute an offer of sale. A reservation will be placed upon receipt of the booking deposit. Generated by Ellington ERP.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Expression of interest");
  downloadBlob(doc, "eoi-" + u.id.toLowerCase() + ".pdf");
}

export function exportDocument(
  docType: string,
  unit: { no: string; typ: string; beds: number; area: number; price: number; psf: number },
  buyer: string,
  ref: string
) {
  const doc = docBase("Ellington Holdings \u00b7 " + docType);
  const pageW = doc.internal.pageSize.getWidth();
  const price = unit.price.toLocaleString("en-US");
  const psf = unit.psf.toLocaleString("en-US");
  const deposit = Math.round(unit.price * 0.1).toLocaleString("en-US");
  const spa = Math.round(unit.price * 0.1).toLocaleString("en-US");
  const constr = Math.round(unit.price * 0.6).toLocaleString("en-US");
  const ho = Math.round(unit.price * 0.2).toLocaleString("en-US");

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(docType, 14, y);
  y += 9;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Ref: " + ref + " \u00b7 Date: 25 Aug 2026", 14, y);
  doc.text("Buyer: " + buyer, 14, y + 5);
  doc.text("Project: Belgravia Heights III \u00b7 Jumeirah Village Circle \u00b7 Dubai, United Arab Emirates", 14, y + 10);
  y += 26;

  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Unit", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Unit", "Typology", "Beds", "Area (sq.ft)", "Price / sq.ft", "Total price"]],
    body: [[unit.no, unit.typ, String(unit.beds), String(unit.area), "AED " + psf, "AED " + price]],
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 4: { halign: "right" }, 5: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Payment plan \u00b7 20/40/40", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Payment milestone", "Share", "Amount"]],
    body: [
      ["Booking deposit \u00b7 10%", "10%", "AED " + deposit],
      ["SPA execution \u00b7 10%", "10%", "AED " + spa],
      ["Construction linked \u00b7 60%", "60%", "AED " + constr],
      ["On handover \u00b7 20%", "20%", "AED " + ho],
      ["Total", "100%", "AED " + price],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 2: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8.5);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("This document was generated automatically in Ellington ERP for " + buyer + " by an authorised user. It is watermarked and versioned into the unit and buyer vaults. RERA advertising permit 88410 \u00b7 DLD project 1884 \u00b7 ORN 21281.", pageW - 28);
  doc.text(note, 14, y, { maxWidth: pageW - 28 });

  docFooter(doc, docType);
  downloadBlob(doc, ref.toLowerCase() + ".pdf");
}

function soaNumbers(u: UnitDoc) {
  const NET_DISCOUNT = 0.05;
  const net = Math.round(u.price * (1 - NET_DISCOUNT));
  const collected = Math.round(net * 0.62);
  const outstanding = net - collected;
  return { net, collected, outstanding };
}

export function exportBuyerStatement(
  buyer: string,
  buyerId: string,
  units: { no: string; st: string; meta: string; price: string; pct: string }[],
  ledger: { date: string; unit: string; desc: string; debit: string; credit: string; balance: string }[],
  totals: { contracted: string; collected: string; outstanding: string }
) {
  const doc = docBase("Ellington Holdings · Buyer statement");
  const pageW = doc.internal.pageSize.getWidth();

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Statement of Account", 14, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Buyer: " + buyer + " \u00b7 " + buyerId, 14, y);
  doc.text("As at 25 Aug 2026 \u00b7 " + units.length + " unit(s) \u00b7 " + units.map((u) => u.no).join(", "), 14, y + 5);
  y += 22;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 22, 31);
  doc.text("Position summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Amount"]],
    body: [
      ["Total contracted", totals.contracted],
      ["Collected", totals.collected],
      ["Outstanding", totals.outstanding],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Units", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Unit", "Status", "Details", "Price", "Collected"]],
    body: units.map((u) => [u.no, u.st, u.meta, u.price, u.pct]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Transaction ledger", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Date", "Unit", "Description", "Debit", "Credit", "Balance"]],
    body: ledger.map((l) => [l.date, l.unit, l.desc, l.debit, l.credit, l.balance]),
    theme: "striped",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("Generated automatically by Ellington ERP. This statement reflects all recorded transactions and current outstanding obligations as at the statement date.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Buyer statement");
  downloadBlob(doc, "statement-" + buyer.toLowerCase().replace(/[^a-z]+/g, "-") + ".pdf");
}

export function exportInvoicesLedger(
  invRows: { no: string; buyer: string; unit: string; inst: string; issued: string; due: string; amount: string; paid: string; status: string }[],
  summary: { issued: string; paid: string; outstanding: string; overdue: string }
) {
  const doc = docBase("Ellington Holdings \u00b7 Invoice register");
  const pageW = doc.internal.pageSize.getWidth();

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Invoices & Statements", 14, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Invoice register \u00b7 auto-issued 14 days before due \u00b7 VAT shown as a separate line", 14, y);
  y += 18;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 22, 31);
  doc.text("Summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Issued this month", "Paid", "Outstanding", "Overdue"]],
    body: [[summary.issued, summary.paid, summary.outstanding, summary.overdue]],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Invoice register", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Invoice", "Buyer", "Unit", "Instalment", "Issued", "Due", "Amount", "Paid", "Status"]],
    body: invRows.map((r) => [r.no, r.buyer, r.unit, r.inst, r.issued, r.due, r.amount, r.paid, r.status]),
    theme: "striped",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 6: { halign: "right" }, 7: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("Generated automatically by Ellington ERP. VAT is shown as a separate line and never baked into the instalment.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Invoice register");
  downloadBlob(doc, "invoice-register.pdf");
}
