import { jsPDF, GState } from "jspdf";
import autoTable from "jspdf-autotable";
import { AC } from "./format";

type ProjectRow = {
  code: string;
  name: string;
  loc: string;
  units: number;
  sold: number;
  gdv: number;
  soldV: number;
  coll: number;
  cons: number;
  status: string;
  flag: boolean;
};

type FinTile = { label: string; value: string; note: string; bad?: boolean };
type FinRow = { code: string; name: string; gdv: string; soldV: string; coll: string; out: string; comm: string; dld: string; net: string };

const AED = "AED ";
const fmt = (n: number) => n.toLocaleString("en-US");

const fmtDate = (d: Date) => d.toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" });
const todayStr = () => fmtDate(new Date());

function watermark(doc: jsPDF, text: string) {
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  doc.saveGraphicsState();
  doc.setGState(new GState({ opacity: 0.12 }));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.setTextColor(20, 22, 31);
  doc.text(text, pageW / 2, pageH / 2, { align: "center", angle: 40 });
  doc.restoreGraphicsState();
}

function downloadBlob(doc: jsPDF, filename: string) {
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export { downloadBlob };

export function exportPortfolioPdf(projects: ProjectRow[], kpis: { label: string; value: string; note: string }[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text("Portfolio position · 5 projects · 850 units · " + todayStr(), 14, 24);

  // KPI summary
  let y = 44;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Summary", 14, y);
  y += 3;
  const half = Math.ceil(kpis.length / 2);
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Note"]],
    body: kpis.map((k) => [k.label, k.value, k.note || ""]),
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Value position by project
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Value position by project", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Code", "Project", "Location", "Units", "Sold", "GDV (M)", "Sold value (M)", "Coll %", "Cons %", "Status"]],
    body: projects.map((p) => [p.code, p.name, p.loc, String(p.units), String(p.sold), fmt(p.gdv), fmt(p.soldV), p.coll + "%", p.cons + "%", p.status]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2, valign: "middle" },
    columnStyles: { 0: { fontStyle: "bold", textColor: [79, 70, 245] } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // Footer
  const lines = doc.splitTextToSize("Collected AED 819.6M · Outstanding receivable AED 502.4M · Overdue AED 31.4M · Units available 316 of 850. Generated by Ellington ERP.", pageW - 28);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  doc.text(lines, 14, y);
  y += lines.length * 5;

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · Portfolio position", 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }

  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "ellington-portfolio-position.pdf";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function exportFinancialsPdf(tiles: FinTile[], rows: FinRow[]) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text("Consolidated financials · 5 SPVs · YTD to " + todayStr(), 14, 24);

  let y = 44;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Note"]],
    body: tiles.map((t) => [t.label, t.value, t.note || ""]),
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Position by project entity", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Code", "Entity", "GDV", "Sold", "Collected", "Outstanding", "Commission", "DLD", "Net cash"]],
    body: rows.map((r) => [r.code, r.name, r.gdv, r.soldV, r.coll, r.out, r.comm, r.dld, r.net]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2, valign: "middle" },
    columnStyles: { 0: { fontStyle: "bold", textColor: [79, 70, 245] } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  const lines = doc.splitTextToSize("Revenue recognised AED 604.2M · Cash collected AED 819.6M · VAT payable AED 8.4M · Commission accrued AED 26.1M. Generated by Ellington ERP.", pageW - 28);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  doc.text(lines, 14, y);

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · Consolidated financials", 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }

  downloadBlob(doc, "ellington-board-pack.pdf");
}

export function reportPdf(title: string, sub: string, meta: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text(sub, 14, 24);

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, 14, y);
  y += 4;
  doc.setFontSize(9.5);
  doc.setTextColor(110, 113, 128);
  doc.setFont("helvetica", "normal");
  const lines = doc.splitTextToSize(meta, pageW - 28);
  doc.text(lines, 14, y);
  y += lines.length * 5 + 6;

  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: [
      ["Report", title],
      ["Generated", todayStr()],
      ["Scope", "All projects"],
      ["Generated by", "Ellington ERP"],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · Reports", 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }

  downloadBlob(doc, "ellington-" + title.replace(/\s+/g, "-").toLowerCase() + ".pdf");
}

type UnitDoc = {
  id: string;
  typ: string;
  beds: number;
  area: number;
  view: string;
  f: number;
  psf: number;
  price: number;
  status: string;
  buyer: string;
};

const line = (doc: jsPDF, x: number, y: number, w: number, color: [number, number, number]) => {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(0.4);
  doc.line(x, y, x + w, y);
};

function docBase(sub: string): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(20, 22, 31);
  doc.rect(0, 0, pageW, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Ellington ERP", 14, 16);
  doc.setFontSize(10.5);
  doc.setTextColor(200, 202, 212);
  doc.setFont("helvetica", "normal");
  doc.text(sub, 14, 24);
  return doc;
}

function docFooter(doc: jsPDF, subject: string) {
  const pageSize = doc.internal.pageSize;
  const pageH = pageSize.getHeight();
  const pageW = pageSize.getWidth();
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(160, 163, 175);
    doc.setFont("helvetica", "normal");
    doc.text("Ellington ERP · " + subject, 14, pageH - 6);
    doc.text("Page " + i + " of " + pageCount, pageW - 14, pageH - 6, { align: "right" });
  }
}

export function exportUnitSoa(u: UnitDoc, milestones: { seq: string; label: string; due: string; pct: string; amount: string; status: string }[], opts?: { discountPct?: number; collected?: number; asOf?: string }) {
  const doc = docBase("Ellington Holdings · Statement of account");
  const pageW = doc.internal.pageSize.getWidth();
  const asOf = opts?.asOf || todayStr();
  const paidRe = /paid|cleared|settled|credited|received/i;
  const collectedCalc = milestones
    .filter((m) => paidRe.test(m.status))
    .reduce((a, m) => a + (Number(String(m.amount).replace(/[^0-9.]/g, "")) || 0), 0);
  const paid = new Set(milestones.filter((m) => paidRe.test(m.status)).map((m) => m.label));
  const { net, collected, outstanding, discountPct } = soaNumbers(u, { discountPct: opts?.discountPct, collected: opts?.collected ?? collectedCalc });
  const buyerName = u.buyer === "—" ? "Unassigned" : u.buyer;
  const today = new Date();
  const nextDueRow = milestones.find((m) => !paid.has(m.label) && (!m.due || new Date(m.due) >= today));
  const nextDue = nextDueRow ? nextDueRow.due : "—";

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Statement of Account", 14, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Buyer: " + buyerName, 14, y);
  doc.text("Unit: " + u.id + " · " + u.typ + " · Level " + u.f + " · " + u.area.toLocaleString("en-US") + " sq.ft · " + u.view + " view", 14, y + 5);
  doc.text("Contract price: " + "AED " + u.price.toLocaleString("en-US") + (discountPct > 0 ? " · net of " + discountPct + "% discount" : ""), 14, y + 10);
  doc.text("State: " + u.status, 14, y + 15);
  y += 26;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 22, 31);
  doc.text("Balance summary · as at " + asOf, 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Amount"]],
    body: [
      ["Net contract price", "AED " + fmt(net)],
      ["Collected to date", "AED " + fmt(collected)],
      ["Outstanding balance", "AED " + fmt(outstanding)],
      ["Next payment due", nextDue],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Payment schedule", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["#", "Milestone", "Due", "%", "Amount", "Status"]],
    body: milestones.map((m) => [m.seq, m.label, m.due, m.pct, m.amount, m.status]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 4: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("This statement is generated automatically by Ellington ERP and reflects the recorded collections and outstanding obligations as at " + asOf + ". Please quote the unit reference when making payment.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Statement of account");
  downloadBlob(doc, "soa-" + u.id.toLowerCase() + ".pdf");
}

export function exportUnitEoi(u: UnitDoc, opts?: { discountPct?: number; asOf?: string }) {
  const doc = docBase("Ellington Holdings · Expression of interest");
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const buyerName = u.buyer === "—" ? "Prospective buyer" : u.buyer;
  const asOf = opts?.asOf || todayStr();
  const discountPct = opts?.discountPct ?? 0;
  const { net } = soaNumbers(u, { discountPct });
  const validity = new Date(Date.now() + 14 * 864e5);
  const expiry = fmtDate(validity);
  const eoiRef = "EOI-" + u.id.toUpperCase().replace(/[^A-Z0-9-]/g, "");

  // Page 1 · Cover
  doc.addPage();
  doc.setFillColor(20, 22, 31);
  doc.rect(0, 40, pageW, 60, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("EXPRESSION OF INTEREST", pageW / 2, 60, { align: "center" });
  doc.setFontSize(13);
  doc.setTextColor(200, 202, 212);
  doc.text("Unit " + u.id + " · " + u.typ + " · " + u.beds + " bedroom", pageW / 2, 72, { align: "center" });
  doc.setFontSize(9);
  doc.setTextColor(170, 173, 184);
  doc.text("Non-binding reservation of interest · prepared by Ellington Holdings Development LLC", pageW / 2, 82, { align: "center" });
  doc.setFontSize(8.5);
  doc.text("Ref " + eoiRef + " · Issued " + asOf + " · Valid until " + expiry, pageW / 2, 90, { align: "center" });

  let y = 116;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(140, 143, 155);
  doc.text("PARTIES", 14, y);
  y += 5;
  autoTable(doc, {
    startY: y,
    head: [["Party", "Details"]],
    body: [
      ["Interested party", buyerName],
      ["Developer", "Ellington Holdings Development LLC · Dubai, United Arab Emirates"],
      ["Subject unit", u.id + " · Level " + u.f + " · " + u.view + " view"],
    ],
    theme: "grid",
    headStyles: { fillColor: [79, 70, 245], fontSize: 8 },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setTextColor(90, 93, 110);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  const coverNote = doc.splitTextToSize(
    "This Expression of Interest confirms that " + buyerName + " has registered interest in the unit described above. It is non-binding, does not constitute an offer of sale, and does not guarantee availability. Availability is subject to the developer's sales inventory and prevailing price list at the time a reservation is placed.",
    pageW - 28
  );
  doc.text(coverNote, 14, y);
  watermark(doc, "NON-BINDING");

  // Page 2 · Project & unit specification
  doc.addPage();
  y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Project & unit specification", 14, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(90, 93, 110);
  const intro = doc.splitTextToSize(
    "The unit is part of a development managed by Ellington Holdings Development LLC under a building permit issued by the relevant authority. The specification below reflects the current published details and may be updated as the project progresses.",
    pageW - 28
  );
  doc.text(intro, 14, y);
  y += intro.length * 5 + 8;
  autoTable(doc, {
    startY: y,
    head: [["Field", "Detail"]],
    body: [
      ["Unit reference", u.id],
      ["Typology", u.typ + " · " + u.beds + " bedroom"],
      ["Floor / view", "Level " + u.f + " · " + u.view + " view"],
      ["Area", u.area.toLocaleString("en-US") + " sq.ft"],
      ["Rate", "AED " + u.psf.toLocaleString("en-US") + " /sq.ft"],
      ["Indicative list price", "AED " + u.price.toLocaleString("en-US")],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setTextColor(20, 22, 31);
  doc.setFontSize(11);
  doc.text("Floor plan & amenities", 14, y);
  y += 5;
  doc.setDrawColor(200, 202, 212);
  doc.setFillColor(244, 245, 247);
  doc.roundedRect(14, y, pageW - 28, 42, 3, 3, "FD");
  doc.setFontSize(9);
  doc.setTextColor(120, 123, 135);
  doc.text("Floor plan — issued on request from the project documentation vault.", pageW / 2, y + 20, { align: "center" });
  y += 50;
  autoTable(doc, {
    startY: y,
    head: [["Amenity", "Availability"]],
    body: [
      ["Fitted kitchen & wardrobes", "Yes"],
      ["Dedicated parking bay", "Yes"],
      ["24/7 building security", "Yes"],
      ["Swimming pool & gym", "Community"],
    ],
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    margin: { left: 14, right: 14 },
  });

  // Page 3 · Indicative payment plan
  doc.addPage();
  y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Indicative payment plan", 14, y);
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  doc.text(discountPct > 0 ? "Shown net of the " + discountPct + "% discount offered at reservation." : "Indicative instalments based on the current list price.", 14, y + 2);
  y += 8;
  const row = (share: number, label: string) => ["AED " + fmt(Math.round(net * share)), share + "%", label];
  autoTable(doc, {
    startY: y,
    head: [["Amount", "Share", "Milestone"]],
    body: [
      row(0.1, "Booking deposit · 10%"),
      row(0.1, "SPA execution · 10%"),
      row(0.6, "Construction linked · 60%"),
      row(0.2, "On handover · 20%"),
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 0: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;
  autoTable(doc, {
    startY: y,
    head: [["Field", "Detail"]],
    body: [
      ["Indicative list price", "AED " + fmt(u.price)],
      ...(discountPct > 0 ? [["Discount", discountPct + "%"] as string[]] : []),
      ["Indicative net price", "AED " + fmt(net)],
      ["Booking deposit (10%)", "AED " + fmt(Math.round(net * 0.1))],
      ["Estimated completion", "Per development programme"],
    ],
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });

  // Page 4 · Terms & signature
  doc.addPage();
  y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Terms & conditions", 14, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90, 93, 110);
  const terms = doc.splitTextToSize(
    "1. This EOI is non-binding and does not create any obligation on either party. 2. Availability and price are subject to change without notice until a formal reservation is confirmed in writing. 3. A reservation and the associated booking deposit will be required before the unit is withdrawn from sale and a binding Sales and Purchase Agreement is issued. 4. All funds relating to the purchase are payable to the project escrow account only; never to any individual. 5. This EOI is valid for fourteen (14) days from the issue date shown on the cover page, after which it lapses unless renewed.",
    pageW - 28
  );
  doc.text(terms, 14, y);
  y += terms.length * 4.6 + 16;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 16;
  const sigY = y;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(140, 143, 155);
  doc.text("INTERESTED PARTY", 16, sigY);
  doc.text("ELLINGTON HOLDINGS · AUTHORISED SIGNATORY", pageW / 2 + 6, sigY);
  line(doc, 16, sigY + 22, 74, [20, 22, 31]);
  line(doc, pageW / 2 + 6, sigY + 22, pageW - 30, [20, 22, 31]);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(150, 153, 165);
  doc.text("Name · signature · date", 16, sigY + 26);
  doc.text("Name · signature · date · company seal", pageW / 2 + 6, sigY + 26);

  docFooter(doc, "Expression of interest");
  downloadBlob(doc, "eoi-" + u.id.toLowerCase() + ".pdf");
}

export function exportDocument(
  docType: string,
  unit: { no: string; typ: string; beds: number; area: number; price: number; psf: number },
  buyer: string,
  ref: string,
  opts?: { project?: string; location?: string; asOf?: string }
) {
  if (/sales offer/i.test(docType)) {
    return exportUnitSalesOffer(unit, buyer, ref, { project: opts?.project, location: opts?.location, asOf: opts?.asOf });
  }

  const doc = docBase("Ellington Holdings \u00b7 " + docType);
  const pageW = doc.internal.pageSize.getWidth();
  const price = unit.price.toLocaleString("en-US");
  const psf = unit.psf.toLocaleString("en-US");
  const deposit = Math.round(unit.price * 0.1).toLocaleString("en-US");
  const spa = Math.round(unit.price * 0.1).toLocaleString("en-US");
  const constr = Math.round(unit.price * 0.6).toLocaleString("en-US");
  const ho = Math.round(unit.price * 0.2).toLocaleString("en-US");
  const asOf = opts?.asOf || todayStr();
  const projectLine = opts?.project
    ? "Project: " + opts.project + (opts.location ? " \u00b7 " + opts.location : "") + " \u00b7 Dubai, United Arab Emirates"
    : "Project: Ellington Holdings Development LLC \u00b7 Dubai, United Arab Emirates";

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(docType, 14, y);
  y += 9;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Ref: " + ref + " \u00b7 Date: " + asOf, 14, y);
  doc.text("Buyer: " + buyer, 14, y + 5);
  doc.text(projectLine, 14, y + 10);
  y += 26;

  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Unit", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Unit", "Typology", "Beds", "Area (sq.ft)", "Price / sq.ft", "Total price"]],
    body: [[unit.no, unit.typ, String(unit.beds), String(unit.area), "AED " + psf, "AED " + price]],
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 4: { halign: "right" }, 5: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Payment plan \u00b7 20/40/40", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Payment milestone", "Share", "Amount"]],
    body: [
      ["Booking deposit \u00b7 10%", "10%", "AED " + deposit],
      ["SPA execution \u00b7 10%", "10%", "AED " + spa],
      ["Construction linked \u00b7 60%", "60%", "AED " + constr],
      ["On handover \u00b7 20%", "20%", "AED " + ho],
      ["Total", "100%", "AED " + price],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 2: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8.5);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("This document was generated automatically in Ellington ERP for " + buyer + " by an authorised user. It is watermarked and versioned into the unit and buyer vaults.", pageW - 28);
  doc.text(note, 14, y, { maxWidth: pageW - 28 });

  docFooter(doc, docType);
  downloadBlob(doc, ref.toLowerCase() + ".pdf");
}

function soaNumbers(u: UnitDoc, opts?: { discountPct?: number; collected?: number }) {
  // B-01: figures come from caller data. Nothing is fabricated in the PDF —
  // a missing discount is treated as 0% and missing collections as AED 0.
  const discountPct = opts?.discountPct ?? 0;
  const net = Math.round(u.price * (1 - discountPct / 100));
  const collected = Math.round(opts?.collected ?? 0);
  const outstanding = Math.max(0, net - collected);
  return { net, collected, outstanding, discountPct };
}

export function exportUnitSalesOffer(
  unit: { no: string; typ: string; beds: number; area: number; price: number; psf: number },
  buyer: string,
  ref: string,
  opts?: { project?: string; location?: string; asOf?: string }
) {
  const doc = docBase("Ellington Holdings · Unit Sales Offer");
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const asOf = opts?.asOf || todayStr();
  const expiry = fmtDate(new Date(Date.now() + 30 * 864e5));
  const projectLine = opts?.project
    ? "Project: " + opts.project + (opts.location ? " · " + opts.location : "") + " · Dubai, United Arab Emirates"
    : "Project: Ellington Holdings Development LLC · Dubai, United Arab Emirates";
  const price = unit.price.toLocaleString("en-US");
  const psf = unit.psf.toLocaleString("en-US");
  const dep10 = Math.round(unit.price * 0.1).toLocaleString("en-US");

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("UNIT SALES OFFER", 14, y);
  y += 9;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Ref: " + ref + " · Issued: " + asOf + " · Offer expires: " + expiry, 14, y);
  doc.text("Buyer: " + buyer, 14, y + 5);
  doc.text(projectLine, 14, y + 10);
  y += 26;

  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Offered unit", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Unit", "Typology", "Beds", "Area (sq.ft)", "Price / sq.ft", "Total price"]],
    body: [[unit.no, unit.typ, String(unit.beds), String(unit.area), "AED " + psf, "AED " + price]],
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 4: { halign: "right" }, 5: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Payment plan · 10/10/60/20", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Payment milestone", "Share", "Amount"]],
    body: [
      ["Booking deposit · 10%", "10%", "AED " + dep10],
      ["SPA execution · 10%", "10%", "AED " + dep10],
      ["Construction linked · 60%", "60%", "AED " + Math.round(unit.price * 0.6).toLocaleString("en-US")],
      ["On handover · 20%", "20%", "AED " + Math.round(unit.price * 0.2).toLocaleString("en-US")],
      ["Total", "100%", "AED " + price],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 8.5 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 2: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 10;
  const sigY = y;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(140, 143, 155);
  doc.text("BUYER / AUTHORISED REPRESENTATIVE", 16, sigY);
  doc.text("ELLINGTON HOLDINGS · AUTHORISED SIGNATORY", pageW / 2 + 6, sigY);
  line(doc, 16, sigY + 24, 78, [20, 22, 31]);
  line(doc, pageW / 2 + 6, sigY + 24, pageW - 30, [20, 22, 31]);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(150, 153, 165);
  doc.text("Name · signature · date", 16, sigY + 28);
  doc.text("Name · signature · date · company seal", pageW / 2 + 6, sigY + 28);
  y += 40;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8.5);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("Acceptance of this offer is subject to the availability of the unit, clearance of the booking deposit into the project escrow account, and the buyer passing KYC / due diligence. This offer lapses unless the booking deposit is received within the validity period shown above. Generated by Ellington ERP; watermarked in preview.", pageW - 28);
  doc.text(note, 14, y, { maxWidth: pageW - 28 });

  watermark(doc, "FOR REVIEW");
  docFooter(doc, "Unit sales offer");
  downloadBlob(doc, ref.toLowerCase() + "-uso.pdf");
}

export function exportBuyerStatement(
  buyer: string,
  buyerId: string,
  units: { no: string; st: string; meta: string; price: string; pct: string }[],
  ledger: { date: string; unit: string; desc: string; debit: string; credit: string; balance: string }[],
  totals: { contracted: string; collected: string; outstanding: string }
) {
  const doc = docBase("Ellington Holdings · Buyer statement");
  const pageW = doc.internal.pageSize.getWidth();

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Statement of Account", 14, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Buyer: " + buyer + " \u00b7 " + buyerId, 14, y);
  doc.text("As at " + todayStr() + " \u00b7 " + units.length + " unit(s) \u00b7 " + units.map((u) => u.no).join(", "), 14, y + 5);
  y += 22;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 22, 31);
  doc.text("Position summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Amount"]],
    body: [
      ["Total contracted", totals.contracted],
      ["Collected", totals.collected],
      ["Outstanding", totals.outstanding],
    ],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 1: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Units", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Unit", "Status", "Details", "Price", "Collected"]],
    body: units.map((u) => [u.no, u.st, u.meta, u.price, u.pct]),
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Transaction ledger", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Date", "Unit", "Description", "Debit", "Credit", "Balance"]],
    body: ledger.map((l) => [l.date, l.unit, l.desc, l.debit, l.credit, l.balance]),
    theme: "striped",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "right", fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("Generated automatically by Ellington ERP. This statement reflects all recorded transactions and current outstanding obligations as at the statement date.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Buyer statement");
  downloadBlob(doc, "statement-" + buyer.toLowerCase().replace(/[^a-z]+/g, "-") + ".pdf");
}

export function exportInvoicesLedger(
  invRows: { no: string; buyer: string; unit: string; inst: string; issued: string; due: string; amount: string; paid: string; status: string }[],
  summary: { issued: string; paid: string; outstanding: string; overdue: string }
) {
  const doc = docBase("Ellington Holdings \u00b7 Invoice register");
  const pageW = doc.internal.pageSize.getWidth();

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Invoices & Statements", 14, y);
  y += 8;
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(110, 113, 128);
  doc.text("Invoice register \u00b7 auto-issued 14 days before due \u00b7 VAT shown as a separate line", 14, y);
  y += 18;

  line(doc, 14, y, pageW - 28, [237, 238, 243]);
  y += 4;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20, 22, 31);
  doc.text("Summary", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Issued this month", "Paid", "Outstanding", "Overdue"]],
    body: [[summary.issued, summary.paid, summary.outstanding, summary.overdue]],
    theme: "striped",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Invoice register", 14, y);
  y += 3;
  autoTable(doc, {
    startY: y,
    head: [["Invoice", "Buyer", "Unit", "Instalment", "Issued", "Due", "Amount", "Paid", "Status"]],
    body: invRows.map((r) => [r.no, r.buyer, r.unit, r.inst, r.issued, r.due, r.amount, r.paid, r.status]),
    theme: "striped",
    headStyles: { fillColor: [20, 22, 31], fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 6: { halign: "right" }, 7: { halign: "right" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  const note = doc.splitTextToSize("Generated automatically by Ellington ERP. VAT is shown as a separate line and never baked into the instalment.", pageW - 28);
  doc.text(note, 14, y);

  docFooter(doc, "Invoice register");
  downloadBlob(doc, "invoice-register.pdf");
}

export function exportCollectionNotice(
  buyer: string,
  unit: string,
  amount: string,
  days: number,
  retention: string,
  refund: string,
  tier?: string
) {
  const doc = docBase("Ellington Holdings \u00b7 Default notice");
  const pageW = doc.internal.pageSize.getWidth();

  let y = 46;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("30-Day Default Notice", 14, y);
  y += 4;
  doc.setFontSize(9.5);
  doc.setTextColor(110, 113, 128);
  doc.setFont("helvetica", "normal");
  doc.text("Issued in accordance with Dubai Law No. 19 of 2017 \u00b7 Terms and Conditions of Sale", 14, y + 5);
  y += 26;

  autoTable(doc, {
    startY: y,
    head: [["Party", "Detail"]],
    body: [
      ["Buyer", buyer],
      ["Unit", unit],
      ["Outstanding amount", "AED " + amount],
      ["Days overdue", String(days)],
      ["Permissible retention", retention],
      ["Refund payable", "AED " + refund],
    ],
    theme: "striped",
    headStyles: { fillColor: [20, 22, 31], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 14;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(90, 93, 110);
  const bodyText = doc.splitTextToSize(
    "Unless the outstanding amount \u00b7 AED " + amount + " \u00b7 is settled within thirty (30) days from the date of this notice, the Developer may, in accordance with the Terms and Conditions of Sale and Dubai Law No. 19 of 2017, treat the contract as terminated and retain up to the permissible percentage of the sums paid, refunding the balance to the buyer.",
    pageW - 28
  );
  doc.text(bodyText, 14, y);
  y += bodyText.length * 4.6 + 8;

  autoTable(doc, {
    startY: y,
    head: [["Notice terms", ""]],
    body: [
      ["Retention tier", tier || "Construction < 60% \u00b7 up to 25% of sums paid"],
      ["Retention held", "AED " + retention],
      ["Refund payable to buyer", "AED " + refund],
      ["Legal review", "Required before issue \u00b7 Escrow & Legal"],
    ],
    theme: "grid",
    headStyles: { fillColor: [79, 70, 245], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: "bold" } },
    margin: { left: 14, right: 14 },
  });

  docFooter(doc, "30-day default notice");
  downloadBlob(doc, "notice-30d-" + buyer.toLowerCase().replace(/[^a-z]+/g, "-") + ".pdf");
}

export function exportOaData(rows: { unit: string; buyer: string; oqood: string; dld: string; deed: string; issued: string; keys: string; oa: string }[]) {
  const header = ["Unit", "Owner", "Oqood", "DLD 4%", "Deed", "Issued", "Keys", "Mollak"];
  const lines = rows.map((r) => [r.unit, r.buyer, r.oqood, r.dld, r.deed, r.issued, r.keys, r.oa].map((c) => '"' + String(c).replace(/"/g, '""') + '"').join(","));
  const csv = "\uFEFF" + [header.join(","), ...lines].join("\r\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "oa-title-data.csv";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

export function exportHandoverCert(unit: string, buyer: string, oqood: string, dld: string) {
  const doc = docBase("Ellington Holdings \u00b7 Handover certificate");
  const pageW = doc.internal.pageSize.getWidth();

  let y = 52;
  doc.setTextColor(20, 22, 31);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Handover Certificate", 14, y, { align: "center" });
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("THIS IS TO CERTIFY THAT", 14, y, { align: "center" });
  y += 12;
  doc.setFont("helvetica", "bolditalic");
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 245);
  doc.text(buyer, 14, y, { align: "center" });
  y += 12;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(90, 93, 110);
  const body = doc.splitTextToSize(
    "having fulfilled all payment and completion obligations under the Sales and Purchase Agreement, is hereby awarded full and vacant possession of the residential unit described below, and its keys are released to the Owner.",
    pageW - 40
  );
  doc.text(body, 14, y, { align: "center" });
  y += body.length * 5.6 + 14;

  autoTable(doc, {
    startY: y,
    head: [["Field", "Detail"]],
    body: [
      ["Unit reference", unit],
      ["Owner", buyer],
      ["Oqood reference", oqood],
      ["DLD 4% registration", dld],
      ["Keys", "Released to owner"],
      ["Owners association", "Registered \u00b7 Mollak"],
      ["Warranty \u00b7 general", "1 year from issue date"],
      ["Warranty \u00b7 structural", "10 years from issue date"],
      ["Issue date", todayStr()],
    ],
    theme: "grid",
    headStyles: { fillColor: [20, 22, 31], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: "bold" } },
    margin: { left: 30, right: 30 },
  });
  y = (doc as any).lastAutoTable.finalY + 16;

  line(doc, 30, y, pageW - 60, [237, 238, 243]);
  y += 8;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110, 113, 128);
  doc.text("Authorised signature \u00b7 Ellington Holdings Development LLC", 14, y, { align: "center" });

  docFooter(doc, "Handover certificate");
  downloadBlob(doc, "handover-cert-" + unit.toLowerCase() + ".pdf");
}
