export const SCR_TITLES: Record<string, string> = {
  dashboard: "Dashboard",
  projects: "Projects",
  financials: "Financials",
  cashflow: "Cashflow",
  reports: "Reports",
  inventory: "Inventory",
  pricing: "Pricing & availability",
  construction: "Construction",
  unit: "Unit",
  buyer: "Buyers",
  payments: "Payments",
  invoices: "Invoices",
  collections: "Collections",
  escrow: "Escrow",
  leads: "Leads",
  booking: "New booking",
  brokers: "Brokers",
  documents: "Documents",
  pipeline: "Handover pipeline",
  snagging: "Snagging",
  deeds: "Title deeds",
  users: "Users & roles",
  settings: "Settings",
  audit: "Audit log",
  mobile: "Executive app",
};

export const STUB_TITLES: Record<string, string> = {
  "stub-projects": "Project list",
  "stub-financials": "Consolidated financials",
  "stub-cashflow": "Cashflow forecast",
  "stub-reports": "Reports & export centre",
  "stub-overview": "Project overview",
  "stub-typologies": "Typology builder",
  "stub-pricing": "Pricing & availability",
  "stub-construction": "Construction progress",
  "stub-brokers": "Brokers & agencies",
  "stub-documents": "Document generator",
  "stub-invoices": "Invoices & statements",
  "stub-pipeline": "Handover pipeline",
  "stub-snagging": "Snagging",
  "stub-deeds": "Title deeds",
};